name: Build and Push to Replicate

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Replicate Docker registry
      run: |
        export DOCKER_CLI_DEBUG=1 | echo "r8_V0ihJgr6QoL9X4CKPv85mfxOIREqcUt3ENUb0" | docker login -u replicate-user --password-stdin r8.im

    - name: Build and Push Docker image
      run: |
        docker buildx build --platform linux/amd64 -t r8.im/ikuharu08/apalapler . --push
